export { ReactComponent as Logotype } from '../icons/pixema.svg';
export { ReactComponent as LogotypeW } from '../icons/pixema-white.svg';
export { ReactComponent as Home } from '../icons/Home.svg';
export { ReactComponent as Trends } from '../icons/Trends.svg';
export { ReactComponent as Favorites } from '../icons/Favorites.svg';
export { ReactComponent as Setting } from '../icons/Setting.svg';
export { ReactComponent as Filters } from '../icons/Filters.svg';
export { ReactComponent as ChevronBtn } from '../icons/Arrow Down.svg';
export { ReactComponent as Menu } from '../icons/Menu.svg';
export { ReactComponent as Close } from '../icons/Close.svg';